Feature update for lts9
cnescatlab/sonar-scanner-catlab pull request #29
Opened 2023-08-07 09:04 UTC by diegorodriguez31

## Proposed changes

Update all tools with their latest version to be compatible with SonarQube LTS 9

## Types of changes

What types of changes does your code introduce to this project?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Issues closed by changes

- [x] Close #28 

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I agree with the [CODE OF CONDUCT](CODE_OF_CONDUCT.md)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

2023-08-07 11:41 UTC, louisjdmartin requested changes
Ok pour ignorer les erreurs type "info" de codacy.

Eventuellement, si il est possible de monter (facilement) la limite de caractères par ligne a 130 je te laisse le faire

2023-08-07 11:41 UTC, louisjdmartin commented on tests/test_cnes_sonar_scanner.py
> +    def get_sonarqube_token(cls):
Si "self" n'est pas utile alors il faut ajouter un `@classmethod`

2023-08-07 11:41 UTC, louisjdmartin commented on tests/test_cnes_sonar_scanner.py
> +    SONARQUBE_TOKEN = ""
Ok pour ignorer cette erreur Codacy

2023-08-08 07:46 UTC, diegorodriguez31 commented
> Ok pour ignorer les erreurs type "info" de codacy.
> 
> Eventuellement, si il est possible de monter (facilement) la limite de caractères par ligne a 130 je te laisse le faire

Malheureusement, ce n'est pas possible de facilement remonter la limite du nombre de ligne sur Codacy.

2023-08-08 09:11 UTC, louisjdmartin approved these changes

2023-08-08 09:41 UTC, merged